### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by ryanhaticus** [dogegarden/dogegarden-landing#15]
Site seems to be down. Doesn't even have a proper A record attached to it.
https://dogehouse.xyz/

@JackCrispy

**Comment by pctfgm** [comment]
![imagen](https://user-images.githubusercontent.com/31021375/112733201-3ae76980-8f1d-11eb-9f19-b097954c6c4a.png)
![imagen](https://user-images.githubusercontent.com/31021375/112733210-4dfa3980-8f1d-11eb-94f9-410a872e5235.png)

It's online

**Comment by ryanhaticus** [comment]
Had a period where it was offline. Weird. Maybe an issue with Vercel.
